#
  #  Copyright (c) 2025 Cofinity-X
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "issuerservice.fullname" . }}
  labels:
    {{- include "issuerservice.server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.issuerservice.autoscaling.enabled }}
  replicas: {{ .Values.issuerservice.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "issuerservice.server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.issuerservice.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "issuerservice.server.selectorLabels" . | nindent 8 }}
        {{- with .Values.issuerservice.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "issuerservice.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.issuerservice.podSecurityContext | nindent 8 }}
      {{- if or .Values.issuerservice.initContainers .Values.customCaCerts }}
      initContainers:
        {{- if .Values.issuerservice.initContainers }}
        {{- toYaml .Values.issuerservice.initContainers | nindent 8 }}
        {{- end }}
        {{- if .Values.customCaCerts }}
        - name: custom-cacerts
          # either use the specified image, or use the default one
          {{- if .Values.issuerservice.image.repository }}
          image: "{{ .Values.issuerservice.image.repository }}:{{ .Values.issuerservice.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/issuerservice:{{ .Values.issuerservice.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.issuerservice.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              cp /opt/java/openjdk/lib/security/cacerts /workdir/
              find /cacerts -type f \( -iname \*.crt -o -iname \*.pem \) -exec echo "{}" \; | while read PEM_FILE_PATH; do
                PEM_FILE=${PEM_FILE_PATH##*/}
                ALIAS=${PEM_FILE%.*}
                echo "adding ${PEM_FILE} with alias ${ALIAS} to cacerts ..."
                keytool -import -noprompt -trustcacerts -alias ${ALIAS} -file ${PEM_FILE_PATH} -keystore /workdir/cacerts -storepass changeit
              done
          securityContext:
            {{- toYaml .Values.issuerservice.securityContext | nindent 12 }}
          volumeMounts:
            - name: custom-cacertificates
              mountPath: /cacerts
            - name: custom-cacerts
              mountPath: /workdir
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.issuerservice.securityContext | nindent 12 }}
          # either use the specified image, or use the default one
          {{- if .Values.issuerservice.image.repository }}
          image: "{{ .Values.issuerservice.image.repository }}:{{ .Values.issuerservice.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/issuerservice:{{ .Values.issuerservice.image.tag | default .Chart.AppVersion }}"
          {{- end }}

          imagePullPolicy: {{ .Values.issuerservice.image.pullPolicy }}
          ports:
          {{- range $key,$value := .Values.issuerservice.endpoints }}
            - name: {{ $key }}
              containerPort: {{ $value.port }}
              protocol: TCP
          {{- end }}
          {{- if .Values.issuerservice.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.issuerservice.endpoints.default.path }}/check/liveness
              port: {{ .Values.issuerservice.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.issuerservice.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.issuerservice.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.issuerservice.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.issuerservice.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.issuerservice.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.issuerservice.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.issuerservice.endpoints.default.path }}/check/readiness
              port: {{ .Values.issuerservice.endpoints.default.port }}
            initialDelaySeconds: {{ .Values.issuerservice.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.issuerservice.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.issuerservice.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.issuerservice.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.issuerservice.readinessProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.issuerservice.resources | nindent 12 }}
          env:
          {{- if .Values.issuerservice.debug.enabled }}
            - name: "JAVA_TOOL_OPTIONS"
            {{- if .Values.issuerservice.debug.suspendOnStart }}
              value: >-
                {{ printf "%s-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=%v"  (ternary "-XX:UseSVE=0 " "" .Values.issuerservice.useSVE) .Values.issuerservice.debug.port}}
            {{- else }}
              value: >-
                {{ printf "%s-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=%v"  (ternary "-XX:UseSVE=0 " "" .Values.issuerservice.useSVE) .Values.issuerservice.debug.port}}
            {{- end }}
          {{- else}}
            - name: "JAVA_TOOL_OPTIONS"
              value: >-
                {{ printf "%s"  (ternary "-XX:UseSVE=0 " "" .Values.issuerservice.useSVE) }}
          {{- end }}


            ######################################
            ## Additional environment variables ##
            ######################################
          {{- range $key, $value := .Values.issuerservice.envValueFrom }}
            - name: {{ $key | quote }}
              valueFrom:
                {{- tpl (toYaml $value) $ | nindent 16 }}
          {{- end }}
          {{- range $key, $value := .Values.issuerservice.env }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
          {{- end }}
          {{- if and (or .Values.issuerservice.envSecretNames .Values.issuerservice.envConfigMapNames) (or (gt (len .Values.issuerservice.envSecretNames) 0) (gt (len .Values.issuerservice.envConfigMapNames) 0)) }}
          envFrom:
          {{- range $value := .Values.issuerservice.envSecretNames }}
            - secretRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- range $value := .Values.issuerservice.envConfigMapNames }}
            - configMapRef:
                name: {{ $value | quote }}
          {{- end }}
          {{- end }}
          volumeMounts:
            {{- if .Values.customCaCerts }}
            - name: custom-cacerts
              mountPath: /opt/java/openjdk/lib/security/cacerts
              subPath: cacerts
            {{- end }}
            - name: "tmp"
              mountPath: "/tmp"
      volumes:
        - name: "configuration"
          configMap:
            name: {{ include "issuerservice.fullname" . }}
            items:
              - key: "logging.properties"
                path: "logging.properties"
        {{- if .Values.customCaCerts }}
        - name: custom-cacertificates
          configMap:
            name: {{ include "issuerservice.fullname" . }}-custom-cacerts
            defaultMode: 0400
        - name: custom-cacerts
          emptyDir:
            sizeLimit: 1Mi
        {{- end }}
        - name: "tmp"
          emptyDir: { }
      {{- with .Values.issuerservice.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.issuerservice.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.issuerservice.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
