#################################################################################
  #  Copyright (c) 2025 Cofinity-X
  #
  #  See the NOTICE file(s) distributed with this work for additional
  #  information regarding copyright ownership.
  #
  #  This program and the accompanying materials are made available under the
  #  terms of the Apache License, Version 2.0 which is available at
  #  https://www.apache.org/licenses/LICENSE-2.0.
  #
  #  Unless required by applicable law or agreed to in writing, software
  #  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  #  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
  #  License for the specific language governing permissions and limitations
  #  under the License.
  #
  #  SPDX-License-Identifier: Apache-2.0
  #################################################################################


---

# this configmap contains all database configuration that is required by the issuerservice runtime.

apiVersion: v1
kind: ConfigMap
metadata:
  name: "issuerservice-datasource-config"
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "issuerservice.labels" . | nindent 4 }}

data:

  ################
  ## POSTGRESQL ##
  ################

  # issuance process
  edc.sql.store.issuanceprocess.datasource: "issuanceprocess"
  edc.datasource.issuanceprocess.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.issuanceprocess.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.issuanceprocess.password: {{ .Values.postgresql.auth.password | quote }}

  # attestation def
  edc.sql.store.attestationdefinitions.datasource: "attestationdefinitions"
  edc.datasource.attestationdefinitions.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.attestationdefinitions.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.attestationdefinitions.password: {{ .Values.postgresql.auth.password | quote }}

  # credential def
  edc.sql.store.credentialdefinitions.datasource: "credentialdefinitions"
  edc.datasource.credentialdefinitions.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.credentialdefinitions.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.credentialdefinitions.password: {{ .Values.postgresql.auth.password | quote }}

  # did documents
  edc.sql.store.didresource.datasource: "didresource"
  edc.datasource.didresource.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.didresource.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.didresource.password: {{ .Values.postgresql.auth.password | quote }}

  # STS Client
  edc.sql.store.stsclient.datasource: "stsclient"
  edc.datasource.stsclient.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.stsclient.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.stsclient.password: {{ .Values.postgresql.auth.password | quote }}

  # Participants
  edc.sql.store.participant.datasource: "participant"
  edc.datasource.participant.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.participant.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.participant.password: {{ .Values.postgresql.auth.password | quote }}

  # Participants Contexts
  edc.sql.store.participantcontext.datasource: "participantcontext"
  edc.datasource.participantcontext.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.participantcontext.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.participantcontext.password: {{ .Values.postgresql.auth.password | quote }}

  # KeyPairs
  edc.sql.store.keypair.datasource: "keypair"
  edc.datasource.keypair.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.keypair.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.keypair.password: {{ .Values.postgresql.auth.password | quote }}

  # JTI validation
  edc.sql.store.jti.datasource: "jti"
  edc.datasource.jti.url: {{ tpl .Values.postgresql.jdbcUrl . | quote }}
  edc.datasource.jti.user: {{ .Values.postgresql.auth.username | quote }}
  edc.datasource.jti.password: {{ .Values.postgresql.auth.password | quote }}